package com.example.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "daily_plans")
data class DailyPlanEntity(
    @PrimaryKey val id: String,
    val userId: String,
    val date: String, // e.g. "2026-10-02" or "Today"
    val summary: String, // High-level executive strategy generated by AI
    val focusScore: Int = 94, // 0-100%
    val timeBlocksJson: String = "[]", // List of TimeBlockItem
    val createdAt: Long = System.currentTimeMillis()
)

data class TimeBlockItem(
    val id: String,
    val startTime: String, // "08:30"
    val endTime: String,   // "10:30"
    val title: String,
    val category: String, // "Deep Focus", "Review", "Execution", "Wellness"
    val isCompleted: Boolean = false,
    val linkedTaskId: String? = null
)
